version: 0.2

phases:
  install:
    commands:
      # Install dependencies
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  build:
    commands:
      # Build the application (if needed)
      - echo "Building the application..."
      - zip -r app.zip lambda_function.py

artifacts:
  files:
    - app.zip