version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running tests..."
      - pytest test_calculator.py --junitxml=report.xml

artifacts:
  files:
    - report.xml
